---

- hosts: all
  tasks:

    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
      packages:
        - nginx
        - OpenSSH
        - curl

    - name: enable ufw ssh
      raw: sudo ufw disable

    - name: Make sure a service nginx is enable
      systemd:
        state: enabled
      name: nginx

    - name: Make sure a service nginx is running
      systemd:
        state: started
      name: nginx
