---
# Setup Nginx
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: zypper -n install python3-virtualenv
  tasks:

  - name: Install a list of packages
    zypper:
      name: "{{ packages }}"
    vars:
      packages:
      - nginx
      - curl
    ignore_errors: true
    become: yes

  - name: Make sure a service nginx is running
    systemd:
      name: nginx
      state: started
    become: yes

  - name: make www
    command: sudo ls -la /var/www
    register: result
    become: yes

  - command: sudo mkdir -p /var/www
    when: result is failed
    become: yes

  - name: make demoapp
    command: sudo ls -la /var/www/demoapp
    register: result
    become: yes

  - command: sudo mkdir -p /var/www/demoapp
    when: result is failed
    become: yes

  - name: Change var
    raw: sudo mount -o remount,exec /var
    become: yes

  - name: Change MOD
    raw: chmod 777 /var/www/demoapp
    become: yes
  

