---
# Setup Nginx
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: zypper -n install python3-virtualenv
  tasks:
    - zypper:
        name: 'http://nginx.org/packages/sles/12/x86_64/RPMS/nginx-1.8.0-1.sles12.ngx.x86_64.rpm'
        state: present
      become: yes

    - name: Make sure a service nginx is running
      systemd:
        state: started
        name: nginx  
      become: yes

    - name: enable service nginx and ensure it is not masked
      systemd:
        name: nginx
        enabled: yes
        masked: no
      become: yes

    - name: Manually create the initial virtualenv
      command: virtualenv /srv/www/htdocs/myenv -p /usr/bin/python creates="/srv/www/htdocs/myenv"
      become: yes

    - name: Copy preinstall to htdocs
      copy:
        src: files/preinstall.txt
        dest: /srv/www/htdocs/
        owner: root
        group: root
        mode: 0755
      become: yes
      
    - name: Install preinstall
      pip: 
        requirements=/srv/www/htdocs/preinstall.txt 
        virtualenv=/srv/www/htdocs/myenv
      become: yes