---
# Setup Nginx
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: zypper -n install python3-virtualenv
  tasks:

    - zypper:
        name: nginx
        update_cache: yes
        type: package
        oldpackage: yes # not required. choices: yes;no. Adds C(--oldpackage) option to I(zypper). Allows to downgrade packages with less side-effects than force. This is implied as soon as a version is specified as part of the package name.
        extra_args: undefined # not required. Add additional options to C(zypper) command.,Options should be supplied in a single line as if given in the command line.
        disable_recommends: yes 
        disable_gpg_check: yes
        state: present
      become: yes

    - name: Make sure a service nginx is running
      systemd:
        state: started
        name: nginx  
      become: yes

    - name: enable service nginx and ensure it is not masked
      systemd:
        name: nginx
        enabled: yes
        masked: no
      become: yes

    - name: Manually create the initial virtualenv
      command: virtualenv /srv/www/htdocs/myenv -p /usr/bin/python creates="/srv/www/htdocs/myenv"
      become: yes

    - name: Copy preinstall to htdocs
      copy:
        src: files/preinstall.txt
        dest: /srv/www/htdocs/
        owner: root
        group: root
        mode: 0755
      become: yes
      
    - name: Install preinstall
      pip: 
        requirements=/srv/www/htdocs/preinstall.txt 
        virtualenv=/srv/www/htdocs/myenv
      become: yes