---
# Setup Nginx
- hosts: all
  tasks:
    - name: Install a list of packages
      apt: name={{ packages }} state=installed
      with_items:
          - nginx
          - OpenSSH
          - curl
      become: yes

    - name: enable ufw ssh
      raw: sudo ufw disable
      become: yes

    - name: Make sure a service nginx is enable
      systemd:
        name: nginx  
        state: enabled
      become: yes

    - name: Make sure a service nginx is running
      systemd:
        name: nginx

        state: started
      become: yes
