---
# Setup Nginx
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson python-virtualenv
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - nginx
      - curl
    become: yes

  - name: enable ufw ssh
    raw: sudo ufw disable
    become: yes

  - name: Make sure a service nginx is running
    systemd:
      name: nginx
      state: started
    become: yes

  - name: make www
    command: sudo ls -la /var/www
    register: result
    ignore_errors: True
    become: yes

  - command: sudo mkdir -p /var/www
    when: result is failed
    become: yes

  - name: make demoapp
    command: sudo ls -la /var/www/demoapp
    register: result
    ignore_errors: True
    become: yes

  - command: sudo mkdir -p /var/www/demoapp
    when: result is failed
    become: yes
  
  - name: install virtualenv
    pip:
      name=virtualenv
      state=present
  become: yes

