---
# Setup Nginx
- hosts: all
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  tasks:

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - nginx
      - curl
    become: yes

  - name: enable ufw ssh
    raw: sudo ufw disable
    become: yes

  - name: Make sure a service nginx is running
    systemd:
      name: nginx
      state: started
    become: yes

  - name: make www
    command: sudo mkdir - /var/www
    when: not p.stat.exists
    become: yes


  - name: make demoapp
    raw: sudo mkdir - /var/www/demoapp
    become: yes
  
  - name: make python-virtualenv
    raw: sudo apt-get install python-virtualenv
    become: yes

  